# Generated by Django 3.1.4 on 2021-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210323_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registartion',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
