# Generated by Django 3.1.3 on 2021-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_forgot_login_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/category/images')),
            ],
        ),
    ]
