# Generated by Django 3.1.3 on 2021-04-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfulio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/portfulio/images')),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/slider/images')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=30)),
                ('City_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='media/subcategory/images')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/team/images')),
            ],
        ),
        migrations.DeleteModel(
            name='forgot',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
