# Generated by Django 3.1.3 on 2021-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210413_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
