# Generated by Django 3.1.3 on 2021-04-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
